project:
  type: website
  output-dir: docs
  
execute:
  cache: false

website:
  title: "Nursing home covid"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - map.qmd
      - graphs.qmd
      - table.qmd
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



