---
title: "Nursing home covid"
---

```{r setup, include=FALSE, cache=TRUE}
source('functions.R')
library(targets)
tar_load_everything(strict=FALSE)
final_data <- SharedData$new(covid_presentation_data)
```


The US Centers for Medicare and Medicaid Services puts out a dataset of covid incidence, deaths, and vaccination at `r nrow(covid_cleaned)` US nursing homes. The data are available at <https://data.cms.gov/covid-19/covid-19-nursing-home-data>. It has info on individual nursing homes, but it can be a little hard to use. I am making it more usable here, trying to make it easier for folks to see how people in nursing homes are being cared for. This uses federal data from the week ending `r max(covid_data$'Week Ending', na.rm=TRUE)`. 

The tabs above have different views of the data. Some quick summaries:

* `r nrow(subset(covid_presentation_data, StaffFullPercent==0))` nursing homes have **zero healthcare staff fully up to date on covid vaccines**.
* `r nrow(subset(covid_presentation_data, StaffFullPercent==100))` nursing homes have all healthcare staff fully up to date on covid vaccines.
* `r nrow(subset(covid_presentation_data, ResidentFullPercent==0))` nursing homes have **zero residents fully up to date on covid vaccines**.
* `r nrow(subset(covid_presentation_data, ResidentFullPercent==100))` nursing homes have all residents fully up to date on covid vaccines.
